name: docdoc_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # state management
  flutter_bloc: ^8.1.5
  # Code generator
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.4.2+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1

  intl: any
  easy_localization: ^3.0.5

  flutter_native_splash: ^2.4.0
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.10+1
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
